import { Products } from "./types/Products";
export const DUMMY_PRODUCTS:Products[] = [
   {id:1, name:"Apple Red", category:"Fruits", price:500, photo:"images/apple1.jpeg", quantity:1},
   {id:2, name:"Apple Green", category:"Fruits", price:800, photo:"images/apple2.webp", quantity:1},
   {id:3, name:"Banana", category:"Fruits", price:900, photo:"images/banana.jpeg", quantity:1},
   {id:4, name:"Orange", category:"Fruits", price:500, photo:"images/orange.webp", quantity:1},
   {id:5, name:"Pizza C1", category:"Pizza", price:1200, photo:"images/pizza1.jpeg", quantity:1},
   {id:6, name:"Pizza C2", category:"Pizza", price:1800, photo:"images/pizza2.jpeg", quantity:1},
   {id:7, name:"Pizza C3", category:"Pizza", price:1400, photo:"images/pizza3.jpeg", quantity:1},
   {id:8, name:"Pizza C4", category:"Pizza", price:2200, photo:"images/pizza4.jpeg", quantity:1},
   {id:9, name:"Burger King", category:"Burger", price:2500, photo:"images/burger1.jpeg", quantity:1},
   {id:10, name:"Burger Combo 1", category:"Burger", price:3000, photo:"images/burger2.jpeg", quantity:1},
   {id:11, name:"Burger Combo 2", category:"Burger", price:2300, photo:"images/burger3.jpeg", quantity:1},
   {id:12, name:"Burger Multiple", category:"Burger", price:14200, photo:"images/burger4.jpeg", quantity:1},
   {id:13, name:"Coffee Black", category:"Coffee", price:500, photo:"images/c1.jpeg", quantity:1},
   {id:14, name:"Capuccino", category:"Coffee", price:1500, photo:"images/c2.jpeg", quantity:1},
   {id:15, name:"Latte", category:"Coffee", price:1200, photo:"images/c3.jpeg", quantity:1},
   {id:16, name:"Americano", category:"Coffee", price:2500, photo:"images/c4.jpeg", quantity:1},
   {id:17, name:"Coctail", category:"Drink", price:3500, photo:"images/d1.jpeg", quantity:1},
   {id:18, name:"Tea", category:"Drink", price:500, photo:"images/d2.webp", quantity:1},
   {id:19, name:"Cola", category:"Drink", price:1200, photo:"images/d3.webp", quantity:1},
   {id:20, name:"Wine", category:"Drink", price:5500, photo:"images/d3.jpeg", quantity:1},
]